name: ous
channels:
  - defaults
dependencies:
  - python
  - cachecontrol
  - jinja2
  - pip:
    - google-api-python-client
    - oauth2client
    - google_auth_oauthlib
    - aiohttp
    - firebase-admin
    - motor

